// export const EMAIL_CHANGED = 'EMAIL_CHANGED';
export const PASSWORD_CHANGED = 'PASSWORD_CHANGED';
export const LOGIN_USER_START = 'login_user_start';
export const LOGIN_USER_SUCCESS = 'login_user_success';
export const LOGIN_USER_ERROR = 'login_user_error';
export const SEARCH_TYPING = 'SEARCH_TYPING';

export const RECEIVE_RANDOM_MOVIE = 'RECEIVE_RANDOM_MOVIE';
export const RECEIVE_GENRES_SUCCESS = 'RECEIVE_GENRES_SUCCESS';
export const RECEIVE_ERROR = 'RECEIVE_ERROR';
export const REQUEST_GENRES = 'REQUEST_GENRES';
export const RECEIVE_MOVIES_SUCCESS = 'RECEIVE_MOVIES_SUCCESS';
export const RECEIVE_MOVIES_ERROR = 'RECEIVE_MOVIES_ERROR';
export const REQUEST_MOVIES = 'REQUEST_MOVIES';
